// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBteUrzZFyolJ8MXYGc-nZH4gQk87snABs',
    appId: '1:347271302887:web:1194b40a564aac77e81c42',
    messagingSenderId: '347271302887',
    projectId: 'scrub-jay-2d537',
    authDomain: 'scrub-jay-2d537.firebaseapp.com',
    databaseURL: 'https://scrub-jay-2d537-default-rtdb.firebaseio.com',
    storageBucket: 'scrub-jay-2d537.appspot.com',
    measurementId: 'G-SZXFQ2SZRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3BVmNZaHRWhv5Fn2cW8eZPdctxE6G340',
    appId: '1:347271302887:android:c513392c597e5e77e81c42',
    messagingSenderId: '347271302887',
    projectId: 'scrub-jay-2d537',
    databaseURL: 'https://scrub-jay-2d537-default-rtdb.firebaseio.com',
    storageBucket: 'scrub-jay-2d537.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBADXYK95rv3-GMf9E6YZ9cAVw6nSNEejE',
    appId: '1:347271302887:ios:813631e294651d3fe81c42',
    messagingSenderId: '347271302887',
    projectId: 'scrub-jay-2d537',
    databaseURL: 'https://scrub-jay-2d537-default-rtdb.firebaseio.com',
    storageBucket: 'scrub-jay-2d537.appspot.com',
    androidClientId: '347271302887-u7trhij24cv92s0iepantvttbp7kv1of.apps.googleusercontent.com',
    iosClientId: '347271302887-eb0d11g1k9jaciofcg81ifg61ul61c9h.apps.googleusercontent.com',
    iosBundleId: 'com.scrubJay.application.scrubJay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBADXYK95rv3-GMf9E6YZ9cAVw6nSNEejE',
    appId: '1:347271302887:ios:813631e294651d3fe81c42',
    messagingSenderId: '347271302887',
    projectId: 'scrub-jay-2d537',
    databaseURL: 'https://scrub-jay-2d537-default-rtdb.firebaseio.com',
    storageBucket: 'scrub-jay-2d537.appspot.com',
    androidClientId: '347271302887-u7trhij24cv92s0iepantvttbp7kv1of.apps.googleusercontent.com',
    iosClientId: '347271302887-eb0d11g1k9jaciofcg81ifg61ul61c9h.apps.googleusercontent.com',
    iosBundleId: 'com.scrubJay.application.scrubJay',
  );
}
